curl \
-X POST \
-H "Content-Type: application/json" \
-H 'access_token: SFW2Mq9QkJbz_GbOIrstENdy3LbDHR4w1fXN43D-dNLSsLTFAJw794cPGWH-IxiN4uDJ8MDdc4TMcM1494Eb95UY7HqGNFuSS8SaVmH3p1LGh2mV91QGBb7aV2vaHCGF4v4V9JXEzJLRcaW_4M2M5tF3SJ4sDS1HR_qxHmqXvqzn_rPd4okmGsVe3NyfBUn7ROuKOGqehG1xzrubD3_c5LZ-FIyOAiqyMOiD72vhtYaRqICeRndiJbZ9FLCg3TXOOk0OPrSTg7HZwsrF72ZTILBS9LHb2SWm3lmf9KuvoKO__7LwT3hBRIZ65bbzCjboGlLfU2W6r65lnGfxGp06bubIGa6wE0' \
-d '{ 
  "recipient":{
    "user_id":"7338592159939223071"
  },
  "message":{
    "text":"hello, Thông báo từ Aura ID"
  }
}' "https://openapi.zalo.me/v2.0/oa/message"